server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
  application:
    name: money
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MONEY
    username: "root"
    password: "0000"
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    show-sql: true